# - alias: 'Alerta de comida'
#   trigger:
#     platform: time
#     hours: '/3'
#     minutes: 0
#     seconds: 0
#   condition:
#     condition: time
#     after: '8:00'
#     before: '23:00'
#   action:
#     - service: notify.henrique
#       data:
#         message: "Já comeu?"
#         title: "Aviso(HB)!!!"
#     - service: notify.lucimara
#       data:
#         message: "Já comeu?"
#         title: "Aviso(HB)!!!"
#
- alias: 'Henrique chegou em casa'
  trigger:
    platform: state
    entity_id: device_tracker.0023551816 #HB
    state: zone.pais_hb
  action:
    - service: notify.henrique
      data:
        message: "HB chegou em casa"
    - service: notify.lucimara
      data:
        message: "HB chegou em casa"

