- platform: nmap_tracker
  hosts: !secret nmap_hosts
  home_interval: 10
  exclude:
   - !secret nmap_exclude

- platform: gpslogger

- platform: traccar
  username: !secret traccar_user
  password: !secret traccar_password
  host: !secret traccar_host
